# Generated by Django 6.0.7 on 2026-07-30 00:19

import accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('volunteer', 'Volunteer'), ('coordinator', 'Coordinator'), ('admin', 'Admin')], default='volunteer', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('accepted_privacy_policy', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills', max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, choices=[('zanzibar_north', 'Zanzibar North'), ('zanzibar_south', 'Zanzibar South'), ('zanzibar_urban_west', 'Zanzibar Urban West'), ('dar_es_salaam', 'Dar es Salaam'), ('pemba_north', 'Pemba North'), ('pemba_south', 'Pemba South')], max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age_group', models.CharField(blank=True, choices=[('16_18', '16-18'), ('19_25', '19-25'), ('26_35', '26-35'), ('36_plus', '36+')], max_length=10)),
                ('nationality', models.CharField(blank=True, choices=[('tanzanian', 'Tanzanian'), ('kenyan', 'Kenyan'), ('ugandan', 'Ugandan'), ('other', 'Other')], max_length=20)),
                ('english_level', models.CharField(blank=True, choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('fluent', 'Fluent')], max_length=20)),
                ('interest_area', models.CharField(blank=True, choices=[('community_development', 'Community Development'), ('youth_mentorship', 'Youth Mentorship'), ('environmental_action', 'Environmental Action'), ('digital_skills', 'Digital Skills Training')], max_length=30)),
                ('volunteered_before', models.BooleanField(blank=True, null=True)),
                ('total_impact_hours', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('rank', models.CharField(choices=[('newcomer', 'Newcomer'), ('active', 'Active'), ('elite', 'Elite'), ('platinum', 'Platinum')], default='newcomer', max_length=20)),
                ('next_rank_threshold_hours', models.DecimalField(decimal_places=1, default=40, max_digits=8)),
                ('is_active_volunteer', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
