"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-y0*1gpc1ne2o*@q+$lk#bs%)-nok4568e2y0+t%*!telp=9@z1"

# SECURITY WARNING: don't run with debug turned on in production!
# On Vercel default to False (production), locally default True
DEBUG = os.environ.get('DEBUG', 'False' if os.environ.get('VERCEL') == '1' else 'True') == 'True'

# --- Hosts for Vercel + local ---
# Vercel sets VERCEL_URL (e.g. zanweb-xyz.vercel.app) and host is zanweb-flax.vercel.app
_allowed_str = os.environ.get('ALLOWED_HOSTS', '')
if _allowed_str:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_str.split(',') if h.strip()]
else:
    # Default for local + Vercel: allow localhost, .vercel.app wildcard and the custom domain
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.vercel.app', 'zanweb-flax.vercel.app', 'zanweb-flax-git-main-drbrilliant360s-projects.vercel.app', 'zanweb-8xo873kzl-drbrilliant360s-projects.vercel.app']
# Always allow Vercel-injected hosts
for _env_host in [os.environ.get('VERCEL_URL'), os.environ.get('VERCEL_BRANCH_URL')]:
    if _env_host and _env_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_env_host)
# Also allow any host from SITE_BASE_URL
_site = os.environ.get('SITE_BASE_URL', '')
if _site:
    from urllib.parse import urlparse
    _host = urlparse(_site).hostname
    if _host and _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)
# Vercel preview suffix - ensure wildcard
if '.vercel.app' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.vercel.app')
# For static export without DB, allow all if no DATABASE_URL (fallback)
if os.environ.get('VERCEL') == '1' and not os.environ.get('DATABASE_URL'):
    # Still need to allow host; already done
    pass


# Application definition

INSTALLED_APPS = [
    "myapp",
    "accounts",
    "programs",
    "volunteering",
    "donations",
    "engagement",
    "dashboard",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database — use Neon if DATABASE_URL set, otherwise fallback to sqlite for Vercel preview/static
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
_database_url = os.environ.get("DATABASE_URL")
if _database_url:
    DATABASES = {
        "default": dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# CSRF — allow Vercel hosts to POST (login, chatbot, etc.)
CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if os.environ.get("CSRF_TRUSTED_ORIGINS") else []
if not CSRF_TRUSTED_ORIGINS or CSRF_TRUSTED_ORIGINS == [""]:
    CSRF_TRUSTED_ORIGINS = []
for _o in ["https://*.vercel.app", "https://zanweb-flax.vercel.app", "https://zanweb-8xo873kzl-drbrilliant360s-projects.vercel.app"]:
    if _o not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_o)
_site_origin = os.environ.get("SITE_BASE_URL")
if _site_origin and _site_origin not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(_site_origin)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization — Tanzania locale
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "sw"

TIME_ZONE = "Africa/Dar_es_Salaam"

USE_I18N = True

USE_TZ = True
USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'myapp', 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = '/login/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── REST Framework ────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# ── CORS ──────────────────────────────────────────────────────
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5500",
    "http://127.0.0.1:5500",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

# ── SimpleJWT ─────────────────────────────────────────────────
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ── Payments (Snippe USSD / Mobile Money) ─────────────────────
PAYMENT_GATEWAY_PROVIDER = os.environ.get('PAYMENT_GATEWAY_PROVIDER', 'snippe')
SNIPPE_API_KEY = os.environ.get('SNIPPE_API_KEY', '')
SNIPPE_WEBHOOK_SECRET = os.environ.get('SNIPPE_WEBHOOK_SECRET', '')
SNIPPE_API_BASE_URL = os.environ.get('SNIPPE_API_BASE_URL', 'https://api.snippe.sh')
SNIPPE_API_VERSION = os.environ.get('SNIPPE_API_VERSION', '2026-01-25')
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'http://127.0.0.1:8000')
# Required — HTTPS only (Snippe VAL_001). Register in Snippe Dashboard → Webhooks.
SNIPPE_WEBHOOK_URL = os.environ.get('SNIPPE_WEBHOOK_URL', '')

