# Generated by Django 4.2.30 on 2026-08-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_donor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaign',
            name='currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
    ]
